import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ButtonAppBar from "../components/navbar"; // Make sure this path is correct
import Footer from "../components/footer"; // Make sure this path is correct

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moosa Al Noor",
  description: "Generated by Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ButtonAppBar /> {/* Navbar component */}
        <main>{children}</main> {/* Render children here */}
        <Footer />
      </body>
    </html>
  );
}
